### PR TITLE
TF-5370 Add Flexible Deployment Options 

### PR DESCRIPTION
**Pull request by anniehedgpeth**
## Background

relates to: [terraform-random-tfe-utility](https://github.com/hashicorp/terraform-random-tfe-utility/pull/118)
Jira: 
* https://hashicorp.atlassian.net/browse/TF-5370
* https://hashicorp.atlassian.net/browse/TF-8610

Relates: https://github.com/hashicorp/ptfedev-infra/pull/526

- [x] This will stay in PR until the [terraform-random-tfe-utility](https://github.com/hashicorp/terraform-random-tfe-utility/compare/ah/tf-5370?expand=1) merges.
- [x] Change modules branch references in this repo to `main`
- [x] Run `ptfe-replicated` Azure tests on this branch (done [here](https://github.com/hashicorp/ptfe-replicated/actions/runs/6263743807))

## How Has This Been Tested

In a follow up PR I will create a workflow that adds another test suite for FDO, but for now, I'm simply changing the `is_legacy_deployment` default to `true` or `false` depending on which I'm testing.

Testing the following:

- [x] `standalone-external` in _legacy_ mode ([link](https://github.com/hashicorp/terraform-azurerm-terraform-enterprise/actions/runs/6201206947/job/16837432784#step:15:456))
- [x] `standalone-mounted-disk` in _legacy_ mode ([link](https://github.com/hashicorp/terraform-azurerm-terraform-enterprise/actions/runs/6201206947/job/16837433194#step:15:2081))
- [x] `public-active-active` in _legacy_ mode ([link](https://github.com/hashicorp/terraform-azurerm-terraform-enterprise/actions/runs/6201206947/job/16837432611#step:15:2121))
- [x] `private-active-active` in _legacy_ mode ([link](https://github.com/hashicorp/terraform-azurerm-terraform-enterprise/pull/224#issuecomment-1721865851))
- [x] `private-tcp-active-active` in _legacy_ mode ([link](https://github.com/hashicorp/terraform-azurerm-terraform-enterprise/pull/224#issuecomment-1721852779))
- [x] `standalone-external` in _FDO_ mode ([link](https://github.com/hashicorp/terraform-azurerm-terraform-enterprise/pull/224#issuecomment-1718449970))
- [x] `standalone-mounted-disk` in _FDO_ mode ([link](https://github.com/hashicorp/terraform-azurerm-terraform-enterprise/pull/224#issuecomment-1718449715))
- [x] `public-active-active` in _FDO_ mode ([link](https://github.com/hashicorp/terraform-azurerm-terraform-enterprise/pull/224#issuecomment-1718450218))
- [x] `private-active-active` in _FDO_ mode ([link](https://github.com/hashicorp/terraform-azurerm-terraform-enterprise/pull/224#issuecomment-1721517962))
- [x] `private-tcp-active-active` in _FDO_ mode ([link](https://github.com/hashicorp/terraform-azurerm-terraform-enterprise/pull/224#issuecomment-1718423905))

### Test Configuration

* Terraform Version: latest
* Any additional relevant variables: `is_legacy_deployment = false`

### CODE REVIEW

**Comment by anniehedgpeth** [comment]
/destroy private-tcp-active-active
/test standalone-mounted-disk
/test standalone-external
/test public-active-active
/test private-active-active
..will this work?

**Comment by anniehedgpeth** [comment]
/test private-active-active destroy=false
`is_legacy_deployment=false`

**Comment by anniehedgpeth** [comment]
/test private-active-active
`var.is_legacy_deployment = true`
* pinning the `load_balancer_waf_rule_set_version` to `3.1` for legacy

**Comment by anniehedgpeth** [comment]
/test private-active-active destroy=false
`var.is_legacy_deployment = true`
* pinning the `load_balancer_waf_rule_set_version` to `3.1` for legacy

**Comment by anniehedgpeth** [comment]
/test private-tcp-active-active destroy=false
var.is_legacy_deployment = true
* pinning the load_balancer_waf_rule_set_version to 3.1 for legacy

**Comment by anniehedgpeth** [comment]
/test private-active-active destroy=false
var.is_legacy_deployment = true

pinning the load_balancer_waf_rule_set_version to 3.1 for legacy

**Review by theoskolnik — DISMISSED** [review]
I trust the tests!

**Review by theoskolnik — APPROVED** [review]

**Pull request merged**
