### PR TITLE
default license secret name to null

### PR DESCRIPTION
**Pull request by anniehedgpeth**
## Background

When running tests for #227 I noticed that the tests broke after 1) changing from using `legacy` to `replicated` in non-FDO deployments, and 2) that when we changed the default to be FDO tests, we needed account for the Replicated license secret not being there if it's an FDO deployment.

## How Has This Been Tested

Below.

The following pass:
- [x] private-active-active
- [x] private-tcp-active-active
- [x] public-active-active
- [x] standalone-external
- [x] standalone-mounted-disk
- [x] private-active-active-replicated
- [x] private-tcp-active-active-replicated
- [x] public-active-active-replicated
- [x] standalone-external-replicated
- [x] standalone-mounted-disk-replicated

### CODE REVIEW

**Comment by anniehedgpeth** [comment]
@theoskolnik This is in a good enough place to merge so that we can properly test your pr.

**Review by amy-hashi — APPROVED** [review]

**Pull request merged**
