### PR TITLE
example-tfvars

### PR DESCRIPTION
**Pull request by sandrampeter**
## Background

[Asana](https://app.asana.com/0/1200681690870921/1201832220012289/f)

### CODE REVIEW

**Review by anniehedgpeth — CHANGES_REQUESTED** [review]
Can you please update these with dummy values like [this one](https://github.com/hashicorp/terraform-azurerm-terraform-enterprise/blob/main/examples/standalone_airgap/terraform.tfvars.example)? Also, did you apply/provision these to make sure they work?

**Comment by sandrampeter** [comment]
closing this as its already added.

**Pull request closed without merging**
