### PR TITLE
license upload

### PR DESCRIPTION
**Pull request by anniehedgpeth**
## Background

This branch implements the usage of the `fixtures/secrets` module for the tests that are run in the `ptfe-replicated` CI.
It also fixes some of the outputs in the `fixtures/secrets` module to be more extensible for future use.

[Asana](https://app.asana.com/0/1181500399442529/1201454602171843/f)

## How Has This Been Tested

This branch was used to run the tests in CircleCI. Here are the [passing tests](https://app.circleci.com/pipelines/github/hashicorp/ptfe-replicated/2718/workflows/1062269d-4cbd-4cf4-8001-bb5a7fc2e4c9). 

I also used this branch to run the pre-check plans on [this PR](https://github.com/hashicorp/ptfedev-infra/pull/356), and they were successful.

## This PR makes me feel

fixtures

### CODE REVIEW

**Comment by anniehedgpeth** [comment]
This PR doesn't require testing with the slash command, as none of those tests are affected by the changes. The only tests that are affected are the ones mentioned in the PR comment that ran in CircleCi.

**Review by aaron-lane — APPROVED** [review]
LGTM ㊙️

**Comment by anniehedgpeth** [comment]
/test all
Using this to test post-merge of [ptfedev-infra/azure and ptfedev-infra/azure-test](https://github.com/hashicorp/ptfedev-infra/pull/356)consuming the ./fixtures/secrets module.

**Comment by anniehedgpeth** [comment]
Oh that's not gonna work, need to make a new branch.

**Pull request merged**
