### PR TITLE
PostgreSQL 12

### PR DESCRIPTION
**Pull request by aaron-lane**
## Background

This branch updates the default PostgreSQL version to 12.

[Asana task](https://app.asana.com/0/1135304898243667/1201068889880687/f)

## How Has This Been Tested

It will be tested here!

## This PR makes me feel

optional gif describing your feelings about this pr

### CODE REVIEW

**Review by sudomateo — APPROVED** [review]

**Comment by sudomateo** [comment]
Azure's single PostgreSQL offering only supports up to PostgreSQL 11. To use PostgreSQL 12, you'll need to use Azure's flexible PostgreSQL offering ([Terraform resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/postgresql_flexible_server)).

**Comment by aaron-lane** [comment]
> Azure's single PostgreSQL offering only supports up to PostgreSQL 11. To use PostgreSQL 12, you'll need to use Azure's flexible PostgreSQL offering ([Terraform resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/postgresql_flexible_server)).

@sudomateo thanks for calling that out! Updated with https://github.com/hashicorp/terraform-azurerm-terraform-enterprise/pull/125/commits/74e20d4a9f68f738d2fc3dbf721099119154dfb2. Let's see how it goes

**Pull request merged**
