### PR TITLE
Chore: Remove tests

### PR DESCRIPTION
**Pull request by nikolasrieble**
## Background

Since the initial implementation of our tests, quite some time has passed, and we have developed other ways of testing both our modules as well as the release. Maintaining the tests and the associated shared infrastructure is a burden that is no longer worth the effort. 

## How Has This Been Tested
This removes tests. Does not change the module.

### CODE REVIEW

**Comment by nikolasrieble** [comment]
\destroy

**Review by miguelhrocha — APPROVED** [review]
Love this <3

**Pull request merged**
